---
title: "Make Dataset"
author: "Sixtus Dakurah"
date: "3/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
library(tidyr); library(pdftools); library(plyr)
library(tidyverse); library(readr); library(tidytext)
library(miscTools); library(stringi); library(rio)
```


```{r}
# set pdf files path 
path.files <- "data-files/covid"

# check stored files
file_vector <- list.files(path = path.files)
# get a head view
file_vector %>% head()
```

```{r}
###########
####  Important Naming Convention for all the pdf files you want to extract the relevant data
####  covid-19-case-report-MONTH-DAY-YEAR
###########

# return the relevant files
pdf_list <- file_vector[grepl("covid-19-case-report", file_vector)]
```



```{r}
corpus_raw <- data.frame("file" = c(NULL),"text" = c(NULL))
# loop through read the raw document, append to the dataframe
for (i in 1:length(pdf_list))
  {
    document_text <-  pdf_text(paste(path.files, "/", pdf_list[i], sep = "")) %>% readr::read_lines()
    
    document <- data.frame("file" = rep(gsub(x =pdf_list[i], pattern = ".pdf", replacement = ""), length(document_text) ), "text" =document_text)
  
    corpus_raw <- rbind(corpus_raw, document) 
  }
```


```{r}
head(corpus_raw)
```

```{r}
# filter by relevant keywords
data.init <- corpus_raw %>% filter(
  
  grepl(( "As of"), text, ignore.case = TRUE)|
    grepl(("Total confirmed and presumptive positive cases"),text, ignore.case = TRUE)|
    grepl(( "Confirmed"),text, ignore.case = TRUE)|
    grepl(("Presumptive"), text, ignore.case = TRUE)|
    grepl(("Total"), text, ignore.case = TRUE)|
    grepl(("Patient was hospitalized"), text, ignore.case = TRUE)|
    grepl(("Patient was not hospitalized"), text, ignore.case = TRUE)|
    # for some reason investigation is messed up
    grepl(("Under Investigation"), text, ignore.case = TRUE)|
    # add the county data
    grepl("Barnstable", text, ignore.case = TRUE)| 
    grepl("Berkshire", text, ignore.case = TRUE)| 
    grepl("Bristol", text, ignore.case = TRUE)| 
    grepl("Dukes", text, ignore.case = TRUE)| 
    grepl("Essex", text, ignore.case = TRUE)| 
    grepl("Franklin", text, ignore.case = TRUE)| 
    grepl("Hampden", text, ignore.case = TRUE)| 
    grepl("Hampshire", text, ignore.case = TRUE)|
    grepl("Middlesex", text, ignore.case = TRUE)|
    grepl("Nantucket", text, ignore.case = TRUE)|
    grepl("Norfolk", text, ignore.case = TRUE)|
    grepl("Plymouth", text, ignore.case = TRUE)|
    grepl("Suffolk", text, ignore.case = TRUE)|
    grepl("Worcester", text, ignore.case = TRUE)|
    grepl("Unknown", text, ignore.case = TRUE)
  
)
```


```{r}
# all the counties in Massachusetts
county<- c("Barnstable","Berkshire", "Bristol","Dukes","Essex","Franklin","Hampden","Hampshire","Middlesex", "Nantucket","Norfolk","Plymouth","Suffolk","Worcester","Unknown")
```


```{r}
# text is factor, convert to characters
data.init$text <- as.character(data.init$text)
head(data.init)
```


```{r}
# get the unique ids/covid files
unique.ids <- unique(data.init$file)

# initialize state and county level frames
state.data <- data.frame(
  "File" = c("Initial"), "DateChar" = c("Initial"), "DateNum" = c("Initial"), "TotalConfirmed" = c(0), "Confirmed" = c(0), 
  "Presumptive" = c(0), "Total" =c(0), "PatientsHospitalized" =c(0),"PatientsNotHospitalized" = c(0),"UnderInvestigation"  = c(0), stringsAsFactors = FALSE)

county.data <- data.frame(
  "File" = c("Initial"), "Barnstable" = c(0), "Berkshire"= c(0), "Bristol"=c(0), "Dukes"=c(0),"Essex"=c(0), "Franklin"=c(0), "Hampden"=c(0),"Hampshire"=c(0),"Middlesex"=c(0), "Nantucket"=c(0), "Norfolk"=c(0), "Plymouth"=c(0), "Suffolk"=c(0), "Worcester"=c(0), "Unknown"=c(0), stringsAsFactors = FALSE
)

for (id in unique.ids)
  
  {
    # select the dataframe for the given time period
    sub.set <- data.init[data.init$file==id, ]
    len.list <- dim(sub.set)[1]
    
    # create county level initial holders
    date.char <- NA; date.num <- NA; tcf <- NA; conf <- NA; pres <- NA
    total <- NA; ph <- NA; pnh <- NA; uinv <- NA;
    
    # create county level initial holders
    Barnstable <- NA; Berkshire <- NA;Bristol<-NA; 
    Dukes <- NA; Essex<- NA; Franklin<- NA; Hampden<- NA; Hampshire <- NA;
    Middlesex<- NA; Nantucket <- NA; Norfolk <- NA; 
    Plymouth <- NA; Suffolk <- NA; Worcester <- NA; Unknown <- NA
    
    for (val in c(1:len.list))
    {
      # select 
      char <- gsub("[^[:alpha:][:space:]]", '', sub.set$text[val])
      char <- gsub("^[[:space:]]+", '', char)
      char <- gsub("[[:space:]]*$", '', char)
      #print(char)
      
      if (str_detect(char, "As of"))
        {
         date.char <- char
         date.num <- gsub("^[[:space:]]+", '', gsub("[^[:digit:][:space:]]", '', sub.set$text[val]) )
        }
      else if (char == "Total confirmed and presumptive positive cases" | char =="Confirmed Cases Reported")
        {
          tcf <- gsub("^[[:space:]]+", '', gsub("[^[:digit:][:space:]]", '', sub.set$text[val]) )
        }
      else if (char == "Confirmed")
        {
          conf <- gsub("^[[:space:]]+", '', gsub("[^[:digit:][:space:]]", '', sub.set$text[val]) )
        }
      else if (char == "Presumptive")
        {
          pres <- gsub("^[[:space:]]+", '', gsub("[^[:digit:][:space:]]", '', sub.set$text[val]) )
        }
      else if (char == "Total")
        {
          total <- gsub("^[[:space:]]+", '', gsub("[^[:digit:][:space:]]", '', sub.set$text[val]) )
        }
      else if (char == "Patient was hospitalized")
        {
          ph <- gsub("^[[:space:]]+", '', gsub("[^[:digit:][:space:]]", '', sub.set$text[val]) )
        }
      else if (char == "Patient was not hospitalized")
        {
          pnh <- gsub("^[[:space:]]+", '', gsub("[^[:digit:][:space:]]", '', sub.set$text[val]) )
        }
      else if (char=="Under Investigation" | char=="Under investigation")
        {
          uinv <- gsub("^[[:space:]]+", '', gsub("[^[:digit:][:space:]]", '', sub.set$text[val]) )
      }
      else if (char %in% county)
        {
          conf.cases <- gsub("^[[:space:]]+", '', gsub("[^[:digit:][:space:]]", '', sub.set$text[val]) )
          
          if (char == county[1]){
            Barnstable <- conf.cases
          } else if(char==county[2]){
            Berkshire <- conf.cases
          }else if(char==county[3]){
            Bristol <- conf.cases
          }else if(char==county[4]){
            Dukes <- conf.cases
          }else if(char==county[5]){
            Essex <- conf.cases
          }else if(char==county[6]){
            Franklin <- conf.cases
          }else if(char==county[7]){
            Hampden <- conf.cases
          }else if(char==county[8]){
            Hampshire <- conf.cases
          }else if(char==county[9]){
            Middlesex <- conf.cases
          }else if(char==county[10]){
            Nantucket <- conf.cases
          }else if(char==county[11]){
            Norfolk <- conf.cases
          }else if(char==county[12]){
            Plymouth <- conf.cases
          }else if(char==county[13]){
            Suffolk <- conf.cases
          }else if(char==county[14]){
            Worcester <- conf.cases
          }else if(char==county[15]){
            Unknown <- conf.cases
          }
      }
    }
    
    vec.state <- c(
      id, date.char, date.num, as.double(tcf), as.double(conf), as.double(pres), 
      as.double(total), as.double(ph), as.double(pnh), as.double(uinv) )
    
    vec.county <- c(id, Barnstable, Berkshire, Bristol,
    Dukes, Essex, Franklin, Hampden, Hampshire,
    Middlesex, Nantucket, Norfolk, 
    Plymouth, Suffolk, Worcester, Unknown)
    
    # add to dataframe
    state.data <- rbind(state.data, vec.state)
    county.data <- rbind(county.data, vec.county)
  }
```

```{r}
head(county.data)
```


```{r}
state.data["Date"] <- paste(state.data$DateChar, state.data$DateNum)
head(state.data)
```


```{r}
drops <- c("DateChar","DateNum")
state.data <- state.data[ , !(names(state.data) %in% drops)]

saveRDS(state.data, file="data-files/StateLevel.rdata")
saveRDS(county.data, file="data-files/CountyLevel.rdata")
```


```{r}
View(state.data)
View(county.data)
```

